# Setup
title:            Spatial Data Forest
tagline:          'Intelligence from Above'
description:      'Engenharia Florestal, Sensoriamento Remoto e Data Science transformados em insights.'
url:              https://britonetorl.github.io # Ajuste conforme seu domínio final
baseurl:          /data-rod

author:
  name:           'Rodrigo Neto'
  email:          'seu-email@exemplo.com'
  url:            https://github.com/data-rod

# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
paginate:         5

# Plugins (Nativos do GitHub Pages)
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# Collections (Define tipos de conteúdo além de posts)
collections:
  projetos:
    output: true
    permalink: /projetos/:path/
  tutoriais:
    output: true
    permalink: /tutoriais/:path/
  sobre:
    output: true
    permalink: /sobre/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projetos"
    values:
      layout: "page" # Criaremos um layout específico depois
