# Dependencies
markdown:         kramdown  # Use kramdown as the markdown processor
highlighter:      pygments

plugins:
  - jekyll-paginate

# Permalinks
permalink:        pretty


# Setup
title:            Spatial Data Forest
tagline:          'Data Analysis'
description:      'Analise de dados voltada para Ciências Florestais.'
url:              http://hyde.getpoole.com
baseurl:          /data-rod/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
