# Dependencies
markdown:         kramdown  # Use kramdown as the markdown processor
highlighter:      pygments

plugins:
  - jekyll-paginate

# Permalinks
permalink:        pretty


# Setup
title:            Spatial Data Forest
tagline:          'Data Analysis'
description:      'Analise de dados espaciais em Ciências Florestais.'
url:              https://github.com/data-rod/data-rod
baseurl:          /data-rod/

author:
  name:           'Rodrigo Neto'
  url:            https://twitter.com/data.rod

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/data-rod/data-rod

collections:
  blog:
    output: true
    permalink: blog/:year/:month/:day/:name/
  projetos:
    output: true
    permalink: projetos/:name/
  tutoriais:
    output: true
    permalink: tutoriais/:name/
  sobre:
    output: true
    permalink: sobre/:name/